class CreateCfgs < ActiveRecord::Migration[5.0]
  def change
    create_table :cfgs do |t|
      t.string :permalink, unique: true

      t.integer :rate
      t.integer :cl_cmdrate
      t.integer :cl_updaterate
      t.float :cl_interp
      t.float :cl_interp_ratio
      t.boolean :cl_lagcompensation

      t.float :volume
      t.float :snd_musicvolume
      t.integer :windows_speaker_config
      t.float :snd_mixahead
      t.integer :snd_headphone_pan_exponent
      t.integer :snd_headphone_pan_radial_weight
      t.boolean :snd_legacy_surround
      t.boolean :snd_mute_losefocus
      t.float :voice_scale
      t.boolean :voice_enable
      t.boolean :lobby_voice_chat_enabled

      t.float :mat_monitorgamma
      t.integer :mat_queue_mode
      t.integer :fps_max
      t.integer :fps_max_menu
      t.boolean :r_dynamic
      t.boolean :r_drawtracers_firstperson

      t.float :sensitivity
      t.float :zoom_sensitivity_ratio_mouse
      t.integer :m_customaccel
      t.boolean :m_rawinput

      t.integer :con_filter_enable
      t.string :con_filter_text
      t.string :con_filter_text_out
      t.integer :mm_dedicated_search_maxping
      t.string :ui_steam_overlay_notification_position
      t.string :cl_downloadfilter
      t.boolean :developer
      t.boolean :con_enable
      t.boolean :player_nevershow_communityservermessage
      t.boolean :gameinstructor_enable
      t.boolean :option_duck_method
      t.boolean :option_speed_method
      t.boolean :cl_forcepreload
      t.boolean :cl_disablehtmlmotd
      t.boolean :cl_autohelp
      t.boolean :cl_showhelp
      t.boolean :cl_disablefreezecam
      t.integer :cl_teammate_colors_show
      t.boolean :cl_autowepswitch
      t.boolean :cl_use_opens_buy_menu
      t.boolean :closeonbuy

      t.float :hud_scaling
      t.float :cl_hud_background_alpha
      t.integer :cl_hud_color
      t.boolean :cl_loadout_colorweaponnames
      t.boolean :cl_hud_healthammo_style
      t.boolean :cl_hud_playercount_showcount
      t.boolean :cl_hud_playercount_pos
      t.integer :viewmodel_fov
      t.float :viewmodel_offset_x
      t.float :viewmodel_offset_y
      t.float :viewmodel_offset_z
      t.integer :viewmodel_presetpos
      t.float :cl_viewmodel_shift_left_amt
      t.float :cl_viewmodel_shift_right_amt
      t.float :cl_bobcycle
      t.integer :cl_bob_lower_amt
      t.float :cl_bobamt_lat
      t.float :cl_bobamt_vert
      t.boolean :hud_showtargetid
      t.boolean :cl_draw_only_deathnotices
      t.boolean :cl_righthand
      t.boolean :cl_showloadout
      t.boolean :cl_showpos
      t.integer :cl_showfps
      t.integer :net_graph
      t.boolean :net_graphproportionalfont

      t.float :cl_hud_radar_scale
      t.float :cl_radar_scale
      t.float :cl_radar_icon_scale_min
      t.boolean :cl_radar_always_centered
      t.boolean :cl_radar_rotate

      t.string :key_esc
      t.string :key_f1
      t.string :key_f2
      t.string :key_f3
      t.string :key_f4
      t.string :key_f5
      t.string :key_f6
      t.string :key_f7
      t.string :key_f8
      t.string :key_f9
      t.string :key_f10
      t.string :key_f11
      t.string :key_f12
      t.string :key_k1
      t.string :key_k2
      t.string :key_k3
      t.string :key_k4
      t.string :key_k5
      t.string :key_k6
      t.string :key_k7
      t.string :key_k8
      t.string :key_k9
      t.string :key_k0
      t.string :key_hyphen
      t.string :key_equals
      t.string :key_backspace
      t.string :key_tab
      t.string :key_q
      t.string :key_w
      t.string :key_e
      t.string :key_r
      t.string :key_t
      t.string :key_y
      t.string :key_u
      t.string :key_i
      t.string :key_o
      t.string :key_p
      t.string :key_lbracket
      t.string :key_rbracket
      t.string :key_bkslash
      t.string :key_capslock
      t.string :key_a
      t.string :key_s
      t.string :key_d
      t.string :key_f
      t.string :key_g
      t.string :key_h
      t.string :key_j
      t.string :key_k
      t.string :key_l
      t.string :key_semicolon
      t.string :key_apostrophe
      t.string :key_enter
      t.string :key_shift
      t.string :key_z
      t.string :key_x
      t.string :key_c
      t.string :key_v
      t.string :key_b
      t.string :key_n
      t.string :key_m
      t.string :key_comma
      t.string :key_period
      t.string :key_fwslash
      t.string :key_ctrl
      t.string :key_alt
      t.string :key_space
      t.string :key_pause
      t.string :key_ins
      t.string :key_home
      t.string :key_pgup
      t.string :key_del
      t.string :key_end
      t.string :key_pgdn
      t.string :key_uparrow
      t.string :key_leftarrow
      t.string :key_downarrow
      t.string :key_rightarrow
      t.string :key_kp_slash
      t.string :key_kp_multiply
      t.string :key_kp_minus
      t.string :key_kp_home
      t.string :key_kp_uparrow
      t.string :key_kp_pgup
      t.string :key_kp_plus
      t.string :key_kp_leftarrow
      t.string :key_kp5
      t.string :key_kp_rightarrow
      t.string :key_kp_end
      t.string :key_kp_downarrow
      t.string :key_kp_pgdn
      t.string :key_kp_enter
      t.string :key_kp_ins
      t.string :key_kp_del
      t.string :key_mouse1
      t.string :key_mwheelup
      t.string :key_mouse3
      t.string :key_mwheeldown
      t.string :key_mouse2
      t.string :key_mouse4
      t.string :key_mouse5

      t.integer :cl_crosshairstyle
      t.integer :cl_crosshaircolor
      t.integer :cl_crosshaircolor_r
      t.integer :cl_crosshaircolor_g
      t.integer :cl_crosshaircolor_b
      t.integer :cl_crosshairalpha
      t.boolean :cl_crosshair_drawoutline
      t.float :cl_crosshair_outlinethickness
      t.float :cl_crosshairsize
      t.float :cl_crosshairthickness
      t.integer :cl_crosshairgap
      t.boolean :cl_crosshairdot

      t.timestamps
    end
    add_index :cfgs, :permalink, unique: true
  end
end
